### ISSUE TITLE
Difference in code in different branches

### ISSUE THREAD

**Issue by ItsTimeToGetOut** [FranciscanLads/X-Y-fit#8]
There is a difference in the FLG repo which are not updated to the parent X-Y branch. therefore, when pushing the changes there it will return a conflict. Therefore that is why @aryapande I was asking you to make the changes here first. Also @Ankur-Srivastava-1 please check out the changes in that repository. Make them here. PR again. and then after everything is fine push these changes in the main repository of franciscanlads.github.io .
All of this could have been avoided if @aryapande would have followed procedure and made the testing changes here.

**Comment by Ankur-Srivastava-1** [comment]
@ItsTimeToGetOut  
I've created another pull request for styling.
Verify and test it and then i'll  make the changes in the other repo too.
